import type { ScannedTrack } from "@/types/track";

/**
 * Sample library used only when running outside Tauri (`npm run dev` in a plain
 * browser), so the UI can be developed without the native backend. The real
 * data path always goes through the Rust `scan_folder` command.
 */
export const SAMPLE_TRACKS: ScannedTrack[] = [
  {
    id: "sample-0001",
    filePath: "/Music/Reggaeton/safaera.mp3",
    fileName: "safaera.mp3",
    format: "mp3",
    hasArtwork: true,
    error: null,
    tags: {
      title: "Safaera [Free Download]",
      artist: "Bad Bunny, Jowell & Randy, Ñengo Flow",
      album: "YHLQMDLG",
      genre: "Latin",
      bpm: 92,
      key: "8A",
      year: 2020,
      energy: null,
      comment: "",
    },
  },
  {
    id: "sample-0002",
    filePath: "/Music/Reggaeton/titi-me-pregunto.flac",
    fileName: "titi-me-pregunto.flac",
    format: "flac",
    hasArtwork: true,
    error: null,
    tags: {
      title: "Tití Me Preguntó",
      artist: "Bad Bunny",
      album: "Un Verano Sin Ti",
      genre: "",
      bpm: 106,
      key: "11A",
      year: 2022,
      energy: null,
      comment: "",
    },
  },
  {
    id: "sample-0003",
    filePath: "/Music/Edits/get-lucky-disclosure.mp3",
    fileName: "get-lucky-disclosure.mp3",
    format: "mp3",
    hasArtwork: false,
    error: null,
    tags: {
      title: "Get Lucky (Disclosure Remix)",
      artist: "Daft Punk",
      album: "",
      genre: "Disco",
      bpm: 124,
      key: "4A",
      year: 2013,
      energy: null,
      comment: "",
    },
  },
  {
    id: "sample-0004",
    filePath: "/Music/Funk/automotivo-bibi.wav",
    fileName: "automotivo-bibi.wav",
    format: "wav",
    hasArtwork: false,
    error: null,
    tags: {
      title: "Automotivo Bibi Fogosa",
      artist: "Bibi Babydoll",
      album: "",
      genre: "Brazilian",
      bpm: 130,
      key: "1A",
      year: 2023,
      energy: null,
      comment: "",
    },
  },
  {
    id: "sample-0005",
    filePath: "/Music/Guaracha/la-fiesta.m4a",
    fileName: "la-fiesta.m4a",
    format: "m4a",
    hasArtwork: true,
    error: null,
    tags: {
      title: "La Fiesta (Aleteo Edit)",
      artist: "DJ Tiesto",
      album: "",
      genre: "",
      bpm: 128,
      key: "9A",
      year: 2021,
      energy: null,
      comment: "",
    },
  },
  {
    id: "sample-0006",
    filePath: "/Music/Dembow/bonbon.mp3",
    fileName: "bonbon.mp3",
    format: "mp3",
    hasArtwork: true,
    error: null,
    tags: {
      title: "Bonbon",
      artist: "El Alfa",
      album: "El Hombre",
      genre: "Latin",
      bpm: 115,
      key: "7A",
      year: 2019,
      energy: null,
      comment: "",
    },
  },
  {
    id: "sample-0007",
    filePath: "/Music/House/insomnia-bootleg.mp3",
    fileName: "insomnia-bootleg.mp3",
    format: "mp3",
    hasArtwork: false,
    error: null,
    tags: {
      title: "Insomnia (Tech House Bootleg) www.djblog.com",
      artist: "Faithless",
      album: "",
      genre: "Trance",
      bpm: 126,
      key: "5A",
      year: 2024,
      energy: null,
      comment: "",
    },
  },
  {
    id: "sample-0008",
    filePath: "/Music/Corrupt/broken-file.mp3",
    fileName: "broken-file.mp3",
    format: "mp3",
    hasArtwork: false,
    error: "read: invalid frame header",
    tags: {
      title: "",
      artist: "",
      album: "",
      genre: "",
      bpm: null,
      key: "",
      year: null,
      energy: null,
      comment: "",
    },
  },
];
